ALTER TABLE contracts.client ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE contracts.contract ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE contracts.client ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE contracts.client ADD COLUMN last_modified TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE contracts.contract ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
