CREATE USER dev WITH PASSWORD 'dev' NOSUPERUSER NOCREATEDB NOCREATEROLE;
GRANT CONNECT ON DATABASE contract TO dev;

\connect contract

CREATE SCHEMA IF NOT EXISTS contracts;
COMMENT ON SCHEMA contracts IS 'Schéma dédié à l''application Contract Service - Gestion des clients et contrats';

GRANT ALL ON SCHEMA contracts TO dev;
GRANT CREATE ON SCHEMA contracts TO dev;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA contracts TO dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA contracts TO dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA contracts GRANT ALL PRIVILEGES ON TABLES TO dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA contracts GRANT ALL PRIVILEGES ON SEQUENCES TO dev;
